export const SITE = {
  name: 'Sahil Langoo',
  title: 'Sahil Langoo | Full Stack Systems Engineer & Systems Architect',
  tagline:
    'Engineering resilient edge systems, high-throughput web architectures & minimalist interfaces.',
  bio: 'Full Stack Systems Engineer at Eresolution Consultancy Services & Co-Founder at SquadCoders. Specializing in TypeScript, Astro 7.3 static architectures, distributed edge proxies, and minimalist UI craft.',
  description:
    'Personal portfolio, engineering journal, and systems catalog of Sahil Langoo. Specializing in TypeScript, Astro 7.3, modern web architecture, edge proxies, and minimalist UI craft.',
  url: 'https://sahillangoo.in',
  author: 'Sahil Langoo',
  legalName: 'Sahil Ahmad Langoo',
  location: 'Kashmir, India',
  detailedLocation: 'Srinagar, Jammu & Kashmir, India 190003',
  email: 'hello@sahillangoo.in',
  personalEmail: 'sahilahmed3066@gmail.com',
  phone: '+91 7006 588 022',
  status:
    'Systems Engineer at Eresolution Consultancy Services & Co-Founder at SquadCoders | Open to high-impact engineering opportunities',
  summary:
    'Full-stack systems engineer with a B.Tech in Computer Science Engineering. Architect of high-throughput web architectures, distributed edge proxies, and technical SEO/AEO pipelines using TypeScript, Astro 7.3, and Cloudflare. Experienced in optimizing Core Web Vitals, Google Search Console indexing, and server latency across production systems.',
  education: [
    {
      institution: 'University of Kashmir (North Campus)',
      location: 'Baramulla, Kashmir, India',
      degree: 'Bachelor of Technology in Computer Science Engineering (B.Tech CSE)',
      period: '2020 - 2023',
      graduationDate: 'December 2023',
      cgpa: '7.07 / 10.0',
      coursework: [
        'Data Structures & Algorithms',
        'Object Oriented Programming',
        'Cloud Computing',
        'Software Engineering',
        'Web Technologies',
        'Capstone: Listify (PHP & MySQL Business Directory)',
      ],
    },
    {
      institution: 'Kashmir Govt Polytechnic',
      location: 'Srinagar, Kashmir, India',
      degree: '3-Year Diploma in Computer Science Engineering',
      period: '2016 - 2019',
      graduationDate: 'July 2019',
      cgpa: '6.22 / 10.0',
      coursework: ['Computer Programming', 'Database Management', 'Computer Networks'],
    },
  ],
  certifications: [
    {
      name: 'Meta Front-End Developer Professional Certificate',
      issuer: 'Meta (Facebook) / Coursera',
      year: '2024',
    },
    {
      name: 'Complete Next.js Developer',
      issuer: 'Frontend Masters (Scott Moss)',
      year: '2024',
    },
    {
      name: 'Ecommerce Platform Using React',
      issuer: 'Scaler Masterclass',
      year: '2024',
    },
    {
      name: 'Crash Course in Python',
      issuer: 'Google / Coursera',
      year: '2023',
    },
    {
      name: 'Full Stack Web Development (Zero To Mastery)',
      issuer: 'Udemy / ZTM (Andrei Neagoie)',
      year: '2023',
    },
  ],
  skills: {
    languages: [
      'TypeScript',
      'JavaScript (ES2023+)',
      'PHP',
      'Python',
      'Typst',
      'SQL',
      'Go',
      'C',
      'C++',
      'HTML5',
      'CSS3 / SASS',
      'Bash',
    ],
    frameworks: [
      'Astro 7.3',
      'React 19',
      'Next.js 16',
      'Hono',
      'Node.js',
      'Express',
      'Tailwind CSS v4',
      'daisyUI 5',
      'Drizzle ORM',
      'Better Auth',
      'Twig',
      'Symfony',
      'Redux Toolkit',
      'TanStack Router',
      'TanStack Query',
      'Partytown',
      'WordPress',
    ],
    cloud: [
      'Cloudflare Pages & Workers',
      'Cloudflare Turnstile',
      'Cloudflare R2 & KV',
      'Cloudflare WAF & DNS',
      'Meta CAPI Gateways',
      'Vercel',
      'Docker',
      'Azure',
      'GitHub Actions CI/CD',
    ],
    databases: [
      'MySQL',
      'PostgreSQL',
      'SQLite / Cloudflare D1',
      'MariaDB',
      'Cloudflare KV',
      'Redis',
      'MongoDB',
    ],
    tools: [
      'Git & GitHub CLI',
      'Wrangler',
      'pnpm',
      'Bun',
      'Postman',
      'Playwright',
      'Sentry',
      'Google Search Console',
      'Google Analytics 4 & GTM',
      'Microsoft Clarity',
      'Technical SEO & Schema.org',
      'Programmatic SEO (pSEO)',
      'Zod',
      'Figma',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'PWA / TWA',
      'LM Studio / Local SLMs (Gemma)',
    ],
  },
  social: {
    github: 'https://github.com/sahillangoo',
    linkedin: 'https://linkedin.com/in/sahillangoo',
    twitter: 'https://x.com/kashurgeek',
    facebook: 'https://www.facebook.com/sahillangoojs/',
    instagram: 'https://www.instagram.com/sahillangoo.in',
    dribbble: 'https://dribbble.com/sahillangoo',
    devto: 'https://dev.to/sahillangoo',
    dailydev: 'https://daily.dev/sahillangoo',
    googleDev: 'https://g.dev/sahillangoo',
    squadcoders: 'https://github.com/SquadCoders',
    email: 'mailto:hello@sahillangoo.in',
    rss: '/rss.xml',
  },
  analytics: {
    cloudflareToken: '0898a42bd33b4506bc0c0912a143f843',
  },
  nav: [
    { label: 'Work', href: '/projects/' },
    { label: 'Writing', href: '/blog/' },
    { label: 'Notes', href: '/notes/' },
    { label: 'Resume', href: '/resume/' },
    { label: 'About', href: '/about/' },
    { label: 'Links', href: '/links/' },
  ],
} as const;

export const NON_INDEXABLE_PATHS = ['/404/', '/rss.xml'] as const;

export const ROBOTS_DISALLOWED_PATHS = ['/api/', '/private/'] as const;
